# These are supported funding model platforms
github: JinsongRoh
ko_fi: JinsongRoh
custom:
  - 'https://github.com/sponsors/JinsongRoh'
  - 'https://paypal.me/JinsongRoh' 
  - 'https://www.buymeacoffee.com/JinsongRoh'
